# Generated by Django 5.0.7 on 2024-07-23 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tareas',
            old_name='nombre',
            new_name='tarea',
        ),
    ]
